global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'vllm'
    static_configs:
      - targets: ['vllm-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
